// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModelSentimentAnalysis
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"0")]
            public float _0 { get; set; }

            [ColumnName(@"1467810369")]
            public float _1467810369 { get; set; }

            [ColumnName(@"Mon Apr 06 22:19:45 PDT 2009")]
            public string Mon_Apr_06_22_19_45_PDT_2009 { get; set; }

            [ColumnName(@"NO_QUERY")]
            public string NO_QUERY { get; set; }

            [ColumnName(@"_TheSpecialOne_")]
            public string __TheSpecialOne_ { get; set; }

            [ColumnName(@"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D")]
            public string text { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"0")]
            public uint _0 { get; set; }

            [ColumnName(@"1467810369")]
            public float _1467810369 { get; set; }

            [ColumnName(@"Mon Apr 06 22:19:45 PDT 2009")]
            public string Mon_Apr_06_22_19_45_PDT_2009 { get; set; }

            [ColumnName(@"NO_QUERY")]
            public string NO_QUERY { get; set; }

            [ColumnName(@"_TheSpecialOne_")]
            public string __TheSpecialOne_ { get; set; }

            [ColumnName(@"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D")]
            public float[] __switchfoot_http___twitpic_com_2y1zl___Awww__that_s_a_bummer___You_shoulda_got_David_Carr_of_Third_Day_to_do_it___D { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
