
// This file was auto-generated by ML.NET Model Builder. 

using MLModelSentimentAnalysis;

// Create single instance of sample data from first line of dataset for model input
MLModel.ModelInput sampleData = new MLModel.ModelInput()
{
    _1467810369 = 1.467811E+09F,
    Mon_Apr_06_22_19_45_PDT_2009 = @"Mon Apr 06 22:19:53 PDT 2009",
    NO_QUERY = @"NO_QUERY",
    __TheSpecialOne_ = @"mattycus",
    __switchfoot_http___twitpic_com_2y1zl___Awww__that_s_a_bummer___You_shoulda_got_David_Carr_of_Third_Day_to_do_it___D = @"@Kenichan I dived many times for the ball. Managed to save 50%  The rest go out of bounds",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual _0 with predicted _0 from sample data...\n\n");


Console.WriteLine($"_0: {0F}");
Console.WriteLine($"_1467810369: {1.467811E+09F}");
Console.WriteLine($"Mon_Apr_06_22_19_45_PDT_2009: {@"Mon Apr 06 22:19:53 PDT 2009"}");
Console.WriteLine($"NO_QUERY: {@"NO_QUERY"}");
Console.WriteLine($"__TheSpecialOne_: {@"mattycus"}");
Console.WriteLine($"__switchfoot_http___twitpic_com_2y1zl___Awww__that_s_a_bummer___You_shoulda_got_David_Carr_of_Third_Day_to_do_it___D: {@"@Kenichan I dived many times for the ball. Managed to save 50%  The rest go out of bounds"}");


Console.WriteLine($"\n\nPredicted _0: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

